version: "3"
services:

  # REVERSE PROXY FOR THE APP
  app-gateway:
    image: nginx:1.17.10
    container_name: app-gateway
    depends_on:
      - frontend
      - customer-service
      - inventory-service
      - order-service
    volumes: 
      - ./app-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # FRONTEND
  frontend:
    image: frontend
    container_name: frontend
    depends_on:
      - api-gateway
    stdin_open: true
    build:
      context: ./frontend
    volumes:
      - './frontend:/usr/app'
      - '/frontend/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true      
    ports:
      - 3000:3000      

  # API GATEWAY (GRAPHQL GATEWAY FOR ALL MICROSERVICES USING APOLLO FEDERATION)
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    depends_on:
      - customer-service
      - inventory-service
      - order-service
    build: 
      context: ./api-gateway
    volumes:
      - './api-gateway/src:/usr/app/src:delegated'
    restart: on-failure

  # CUSTOMER SERVICE
  customer-service:
    image: customer-service
    container_name: customer-service
    build: 
      context: ./customer-service
    volumes:
      - './customer-service/src:/usr/app/src:delegated'
    restart: on-failure
  
  # INVENTORY SERVICE    
  inventory-service:
    image: inventory-service
    container_name: inventory-service
    build: 
      context: ./inventory-service
    volumes:
      - './inventory-service/src:/usr/app/src:delegated'
    restart: on-failure
  
  # ORDER SERVICE    
  order-service:
    image: order-service
    container_name: order-service
    build: 
      context: ./order-service
    volumes:
      - './order-service/src:/usr/app/src:delegated'
    restart: on-failure
